version: '3'

services:
  app:
    container_name: FastAPI
    build: ./docker
    volumes:
      - ./src:/var/www/html
    ports:
      - "3000:3000"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 3000
