@kurichi_email=yuuyapp080@gmail.com
@kurichi_pass=password
@test_email=test@example.com
@test_pass=passpass

# @name login
POST https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyBU2vQq2uylUITbmd8id5jbZWNuCmAswE0 HTTP/1.1
Content-Type: application/json

{
    "email":"{{test_email}}",
    "password":"{{test_pass}}",
    "returnSecureToken":true
}
###

@token = {{login.response.body.$.idToken}}
@Kurichi_uid = PGF8whP6JTR7apGjkYFMay1IbbC3
@test_uid=OxUbEbMAsmPP2A71FfU7DQuMBTB3
@yammer_uid=EieJoM9ChXfyfVMGoJbwQWLWvXj2

# @host = http://localhost/
@host = http://27.133.132.254/

### login
POST {{host}} HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "push_token": ""
}

### send chat
POST {{host}}chat HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "to": "{{Kurichi_uid}}",
    "text": "helloworld:Warning: "
}

###
GET {{host}}chat?id=3 HTTP/1.1
Authorization: {{token}}

###
POST {{host}}friend HTTP/1.1
Authorization: {{token}}
Content-Type: application/json

{
    "uid": "{{Kurichi_uid}}"
}

###
GET {{host}}friend HTTP/1.1
Authorization: {{token}}

###
GET {{host}}user?uid={{Kurichi_uid}} HTTP/1.1
Authorization: {{token}}