FROM golang:1.19.2-alpine3.15

RUN apk update &&  apk add git
WORKDIR /go/src/app
COPY ./app ./
RUN export GO_ENV=/go/src/app/
RUN export GOOGLE_APPLICATION_CREDENTIALS="/go/src/app/service-account-file.json"

RUN go get github.com/uudashr/gopkgs/v2/cmd/gopkgs \
    github.com/ramya-rao-a/go-outline \
    github.com/nsf/gocode \
    github.com/acroca/go-symbols \
    github.com/fatih/gomodifytags \
    github.com/josharian/impl \
    github.com/haya14busa/goplay/cmd/goplay \
    github.com/go-delve/delve/cmd/dlv \
    golang.org/x/lint/golint \
    golang.org/x/tools/gopls

# Hot Reload
RUN go install github.com/cosmtrek/air@v1.29.0

CMD ["air", "-c", ".air.toml"]